### ISSUE TITLE
Contacto

### ISSUE THREAD

**Issue by mariofs** [prossigo/Mariofs#6]
* Plantilla web
* Formulario

**Comment by mariofs** [comment]
Diseño digital pantalla contacto creada.

**Comment by delfinbeta** [comment]
Issue incorrecto, era el #1 Diseño de Pantalla Contacto

**Comment by delfinbeta** [comment]
Frontend creado, continuaré con el backend, para el envío del correo y suscripción al Blog

**Comment by delfinbeta** [comment]
Funcionalidad del formulario de Contacto lista.
